'use strict';

const CONFIG = Object.freeze({ maxLives: 3, maxEnergy: 100, wrongEnergy: 10, multipleChoiceScore: 100 });
const BETWEEN_GAME_TRANSITION_MS = 5000;
const CITY_TRANSITION_MS = 3000;
const ASSET_ROOTS = Object.freeze({ optimized:'assets/optimized', ui:'assets/ui', sfx:'assets/sounds' });
const ASSETS = Object.freeze({
  start:`${ASSET_ROOTS.ui}/start_screen.png`, how:`${ASSET_ROOTS.ui}/how_to_play.png`, hud:`${ASSET_ROOTS.ui}/hud_panel.png`, life:`${ASSET_ROOTS.ui}/life.png`,
  question:`${ASSET_ROOTS.ui}/question_panel_clean.png`, feedback:`${ASSET_ROOTS.ui}/feedback_panel.png`, inventoryPanel:`${ASSET_ROOTS.ui}/inventory_panel.png`, emergencyRescue:`${ASSET_ROOTS.ui}/emergency_rescue_panel.png`, routeSelection:`${ASSET_ROOTS.ui}/route_selection.png`,
  home:`${ASSET_ROOTS.optimized}/backgrounds/home_bedroom.webp`, blackoutStreet:`${ASSET_ROOTS.optimized}/backgrounds/master_blackout_street.webp`, supplyRoom:`${ASSET_ROOTS.optimized}/backgrounds/supermarket_supply_room.webp`, serviceTunnels:`${ASSET_ROOTS.optimized}/backgrounds/metro_maintenance_room.webp`, cityStreets:`${ASSET_ROOTS.optimized}/backgrounds/city_center.webp`,
  phone:`${ASSET_ROOTS.optimized}/interactive/phone.png`, items:Object.freeze({waterBottle:`${ASSET_ROOTS.optimized}/items/water_bottle.png`,firstAidKit:`${ASSET_ROOTS.optimized}/items/first_aid_kit_open.png`,chocolateBar:`${ASSET_ROOTS.optimized}/items/chocolate_bar.png`,batteries:`${ASSET_ROOTS.optimized}/items/batteries.png`,emergencyAccessCard:`${ASSET_ROOTS.optimized}/items/emergency_access_card.png`}),
  interactive:Object.freeze({helicopter:`${ASSET_ROOTS.optimized}/interactive/helicopter.png`}),collectiblesRoot:`${ASSET_ROOTS.optimized}/collectibles`,achievementsRoot:`${ASSET_ROOTS.optimized}/achievements`
});
const SFX = Object.freeze({click:`${ASSET_ROOTS.sfx}/button_click.wav`,select:`${ASSET_ROOTS.sfx}/interface_select.wav`,correct:`${ASSET_ROOTS.sfx}/correct.wav`,wrong:`${ASSET_ROOTS.sfx}/wrong.wav`,lifeLost:`${ASSET_ROOTS.sfx}/life_lost.wav`,inventory:`${ASSET_ROOTS.sfx}/inventory_open.wav`,itemPickup:`${ASSET_ROOTS.sfx}/item_pickup.wav`,complete:`${ASSET_ROOTS.sfx}/mission_complete.wav`});
const AUDIO_TRACKS = Object.freeze({cityRain:`${ASSET_ROOTS.optimized}/sounds/city_rain.mp3`,underground:`${ASSET_ROOTS.optimized}/sounds/underground.mp3`,danger:`${ASSET_ROOTS.optimized}/sounds/danger.mp3`,exploration:`${ASSET_ROOTS.optimized}/sounds/exploration.mp3`,finalEscape:`${ASSET_ROOTS.optimized}/sounds/final_escape.mp3`});
const GRAMMAR_DATA = Object.freeze([
  {sentence:'Oh no! The lights ___!',options:['go out','went out','have gone out','are going out'],answer:'have gone out'},
  {sentence:'The power ___ across the city two minutes ago.',options:['fails','failed','is failing','has failed'],answer:'failed'},
  {sentence:'Emergency teams ___ more information soon.',options:['send','sent','are sending','will send'],answer:'will send'},
  {sentence:'Listen! Someone ___ on the door.',options:['knocks','knocked','has knocked','is knocking'],answer:'is knocking'}
]);
const STREET_SIGNALS_DATA = Object.freeze([
  {sentence:'The emergency system usually ___ automatically during a blackout.',options:['activates','is activating','activated','has activated'],answer:'activates'},
  {sentence:'Look! The traffic lights ___ again.',options:['work','worked','are working','have worked'],answer:'are working'},
  {sentence:'The police ___ this street ten minutes ago.',options:['close','are closing','closed','have closed'],answer:'closed'},
  {sentence:'Emergency teams ___ three people so far.',options:['rescue','are rescuing','rescued','have rescued'],answer:'have rescued'},
  {sentence:'Right now, engineers ___ the damaged power line.',options:['repair','are repairing','repaired','have repaired'],answer:'are repairing'}
]);
const SUPPLY_SEARCH_DATA = Object.freeze([
  {sentence:'When the blackout started, I ___ (look) for some water.',answer:'was looking',reward:'Water Bottle',asset:ASSETS.items.waterBottle},
  {sentence:'The first-aid supplies ___ already ___ (pack).',answer:'have been packed',reward:'First Aid Kit',asset:ASSETS.items.firstAidKit},
  {sentence:'By the time we reached the supply room, someone ___ (take) most of the food.',answer:'had taken',reward:'Chocolate Bar',asset:ASSETS.items.chocolateBar},
  {sentence:'Emergency batteries ___ (store) in this room every week.',answer:'are stored',reward:'Batteries',asset:ASSETS.items.batteries}
]);
const SIGNAL_SCANNER_DATA = Object.freeze([
  {options:['The tunnel lights have stopped working just.','The tunnel lights just have stopped working.','The tunnel lights have just stopped working.','The tunnel lights are just stopped working.'],answer:'The tunnel lights have just stopped working.'},
  {options:['The maintenance team has been checking the cables since twenty minutes.','The maintenance team has been checking the cables for twenty minutes.','The maintenance team is checking the cables for twenty minutes.','The maintenance team checked the cables since twenty minutes.'],answer:'The maintenance team has been checking the cables for twenty minutes.'},
  {options:['The emergency doors were locked when the power failed.','The emergency doors have locked when the power failed.','The emergency doors were locking when the power has failed.','The emergency doors have been locking when the power failed.'],answer:'The emergency doors were locked when the power failed.'},
  {options:['The signal has already restored by the engineers.','The signal was already restore by the engineers.','The signal has already been restored by the engineers.','The signal has been already restore by the engineers.'],answer:'The signal has already been restored by the engineers.'}
]);
const ERROR_DETECTOR_DATA = Object.freeze([
  {sentence:'The engineers has been working on the emergency signal since midnight.',segments:['The engineers','has been working','on the emergency signal','since midnight'],wrong:'has been working',correction:'have been working',corrected:'The engineers have been working on the emergency signal since midnight.'},
  {sentence:"The rescue team hasn't found the missing driver already.",segments:['The rescue team',"hasn't found",'the missing driver','already'],wrong:'already',correction:'yet',corrected:"The rescue team hasn't found the missing driver yet."},
  {sentence:'The emergency lights were repaired when the second blackout has started.',segments:['The emergency lights','were repaired','when','the second blackout has started'],wrong:'the second blackout has started',correction:'the second blackout started',corrected:'The emergency lights were repaired when the second blackout started.'},
  {sentence:'The police have blocked this street two hours ago.',segments:['The police','have blocked','this street','two hours ago'],wrong:'have blocked',correction:'blocked',corrected:'The police blocked this street two hours ago.'}
]);
const RESCUE_DATA = Object.freeze([
  {sentence:'Emergency workers usually ___ special radios during rescue operations.',options:['use','are using','used','have used'],answer:'use'},
  {sentence:'When we lost contact, the rescue team ___ towards the river.',options:['moved','was moving','has moved','had moved'],answer:'was moving'},
  {sentence:'Good news! Your emergency signal ___.',options:['receives','received','has been received','is receiving'],answer:'has been received'},
  {sentence:"We couldn't enter the building because someone ___ the main door.",options:['locks','locked','has locked','had locked'],answer:'had locked'},
  {sentence:"Don't worry. Another rescue team ___ to your location.",options:['sends','was sent','has been sent','will be sent'],answer:'will be sent'}
]);

class AudioManager {
  constructor(){let saved={};try{saved=JSON.parse(localStorage.getItem('blackout.audio')||'{}')||{};}catch{}this.musicVolume=this.validVolume(saved.musicVolume,.35);this.sfxVolume=this.validVolume(saved.sfxVolume,.70);this.muted=typeof saved.muted==='boolean'?saved.muted:false;this.enabled=false;this.music=null;this.ambience=null;this.cache=new Map();}
  validVolume(value,fallback){const number=Number(value);return Number.isFinite(number)&&number>=0&&number<=1?number:fallback;}
  unlock(){this.enabled=true;}
  persist(){localStorage.setItem('blackout.audio',JSON.stringify({musicVolume:this.musicVolume,sfxVolume:this.sfxVolume,muted:this.muted}));}
  sfx(name){if(!this.enabled||this.muted||!SFX[name])return;let base=this.cache.get(name);if(!base){base=new Audio(SFX[name]);base.preload='metadata';this.cache.set(name,base);}const sound=base.cloneNode();sound.volume=this.sfxVolume;sound.play().catch(()=>{});}
  playLoop(channel,name,volumeScale=1){if(!this.enabled||!AUDIO_TRACKS[name])return;const current=this[channel];if(current?.dataset.track===name)return;this.stopLoop(channel);const track=new Audio(AUDIO_TRACKS[name]);track.dataset.track=name;track.dataset.scale=String(volumeScale);track.loop=true;track.preload='none';track.volume=0;this[channel]=track;track.play().then(()=>this.fade(track,this.targetVolume(track))).catch(()=>{});}
  targetVolume(track){return this.muted?0:this.musicVolume*Number(track?.dataset.scale||1);}
  fade(track,target){clearInterval(track.fadeTimer);track.fadeTimer=setInterval(()=>{const difference=target-track.volume;if(Math.abs(difference)<.025){track.volume=target;clearInterval(track.fadeTimer);return;}track.volume=Math.max(0,Math.min(1,track.volume+Math.sign(difference)*.02));},40);}
  stopLoop(channel){const track=this[channel];if(!track)return;clearInterval(track.fadeTimer);track.pause();this[channel]=null;}
  setMusicVolume(value){this.musicVolume=this.validVolume(value,.35);for(const track of [this.music,this.ambience])if(track)this.fade(track,this.targetVolume(track));this.persist();}
  setSfxVolume(value){this.sfxVolume=this.validVolume(value,.70);this.persist();}
  toggleMute(){this.muted=!this.muted;for(const track of [this.music,this.ambience])if(track)this.fade(track,this.targetVolume(track));this.persist();return this.muted;}
}
class GameState {reset(){Object.assign(this,{lives:3,energy:100,score:0,streak:0,maxStreak:0,secrets:0,livesLost:0,correctAnswers:0,firstAttemptCorrect:0,wrongAnswers:0,emergencyRescueCount:0,inventory:[],achievements:[],game:1,questionIndex:0,gameProgress:0,energyEvents:new Set(),rescueIndex:0,rescueCorrect:0,serviceTunnelsCompleted:false,cityStreetsCompleted:false,mainBridgeCompleted:false,selectedRoute:null,startedAt:0});}}

const audio=new AudioManager(),state=new GameState();state.reset();
const screen=document.querySelector('#screen'),hud=document.querySelector('#hud'),feedback=document.querySelector('#feedback'),modalRoot=document.querySelector('#modal-root'),audioToggle=document.querySelector('#audio-toggle');
let timerId=0,feedbackId=0,tooltipId=0,routeMessageId=0,locked=false,transitionId=0;
const DEV_TARGET=new URLSearchParams(location.search).get('dev'),LOCAL_DEV_HOSTS=new Set(['127.0.0.1','localhost','::1','[::1]']);
function armDevAudioUnlock(){if(audio.enabled)return;const unlock=()=>{audio.unlock();audio.playLoop('ambience','cityRain',.7);document.removeEventListener('pointerdown',unlock,true);document.removeEventListener('keydown',unlock,true);};document.addEventListener('pointerdown',unlock,{capture:true,once:true});document.addEventListener('keydown',unlock,{capture:true,once:true});}
function button(className,label){const element=document.createElement('button');element.className=`hotspot ${className}`;element.type='button';element.setAttribute('aria-label',label);return element;}
function artComposition(src,alt=''){const frame=document.createElement('div');frame.className='art-composition';const image=document.createElement('img');image.className='art-screen';image.src=src;image.alt=alt;image.draggable=false;frame.append(image);return frame;}
function preloadImage(src){return new Promise(resolve=>{const image=new Image();image.onload=resolve;image.onerror=resolve;image.src=src;});}
function clearScreen(){clearTimeout(transitionId);screen.replaceChildren();screen.className='screen';screen.style.backgroundImage='';}
function showFeedback(text,type='info',duration=1200){clearTimeout(feedbackId);feedback.textContent=text;feedback.className=`feedback ${type} show`;feedbackId=setTimeout(()=>feedback.className='feedback',duration);}
function showTooltip(anchor,text){clearTimeout(tooltipId);anchor.parentElement.querySelectorAll('.button-tooltip').forEach(item=>item.remove());const tip=document.createElement('div');tip.className='button-tooltip';tip.textContent=text;tip.style.left=`${anchor.offsetLeft+anchor.offsetWidth/2}px`;tip.style.top=`${anchor.offsetTop-6}px`;anchor.parentElement.append(tip);requestAnimationFrame(()=>tip.classList.add('show'));tooltipId=setTimeout(()=>{tip.classList.remove('show');setTimeout(()=>tip.remove(),200);},1500);}
function updateAudioIcon(){audioToggle.textContent=audio.muted?'🔇':'🔊';audioToggle.setAttribute('aria-label',audio.muted?'Audio muted — open settings':'Open audio settings');}
function updateHud(){const lives=document.querySelector('#hud-lives');lives.replaceChildren(...Array.from({length:CONFIG.maxLives},(_,index)=>{const heart=document.createElement('span');heart.className=`life-dot ${index>=state.lives?'lost':''}`;return heart;}));document.querySelector('#energy-fill').style.width=`${state.energy}%`;const energyBar=document.querySelector('.energy-bar');energyBar.classList.toggle('warning',state.energy>=21&&state.energy<=50);energyBar.classList.toggle('critical',state.energy<=20);document.querySelector('#hud-energy').textContent=`${state.energy} energy`;document.querySelector('#hud-score').textContent=state.score.toLocaleString();document.querySelector('#hud-secrets').textContent=`${state.secrets}/5`;document.querySelector('#backpack-count').textContent=`${state.inventory.length}/4`;}
function loseEnergyForWrongAnswer(){state.energy=Math.max(0,state.energy-5);updateHud();if(state.energy===0){showEnergyRecovery();return true;}setTimeout(()=>{if(state.energy<=20)showFeedback('LOW ENERGY — Use a supply if needed.','bad',1500);},650);return false;}
function startTimer(){clearInterval(timerId);timerId=setInterval(()=>{const seconds=Math.floor((Date.now()-state.startedAt)/1000);document.querySelector('#hud-time').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;},1000);}
function showStart(){clearInterval(timerId);audio.stopLoop('music');audio.stopLoop('ambience');hud.classList.add('hidden');clearScreen();const composition=artComposition(ASSETS.start,'BLACKOUT start screen');const start=button('start-btn','Start mission'),settings=button('start-settings','Audio settings'),inventory=button('start-inventory','Inventory'),achievements=button('start-achievements','Achievements');start.onclick=()=>{audio.unlock();audio.sfx('click');state.reset();audio.playLoop('music','exploration');showHow();};settings.onclick=event=>{event.stopPropagation();audio.unlock();audio.sfx('click');toggleAudioPanel(true);};inventory.onclick=()=>showTooltip(inventory,'Available during mission');achievements.onclick=()=>showTooltip(achievements,'Unlock during missions');composition.append(start,settings,inventory,achievements);screen.append(composition);}
function showHow(){clearScreen();const composition=artComposition(ASSETS.how,'How to play BLACKOUT');const back=button('how-back','Back to menu'),go=button('how-go','Begin mission');go.textContent='BEGIN MISSION';back.onclick=()=>{audio.sfx('click');showStart();};go.onclick=()=>{audio.sfx('click');beginMission();};composition.append(back,go);screen.append(composition);}
function beginMission(){if(!state.startedAt)state.startedAt=Date.now();hud.classList.remove('hidden');updateHud();startTimer();showHome();}
function showHome(){clearScreen();audio.playLoop('ambience','cityRain',.7);screen.style.backgroundImage=`url('${ASSETS.home}')`;const title=document.createElement('div');title.className='scene-title';title.innerHTML='<strong>Home Bedroom</strong><span>The city just went dark. Find a source of information.</span>';const phone=document.createElement('img');phone.src=ASSETS.phone;phone.className='phone';phone.alt='Ringing emergency phone';phone.tabIndex=0;const callout=document.createElement('div');callout.className='phone-callout';callout.textContent='INCOMING EMERGENCY ALERT';const open=()=>{audio.sfx('select');showQuestion();};phone.onclick=open;phone.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open();}};screen.append(title,phone,callout);}
function currentGrammarData(){return state.game===5?ERROR_DETECTOR_DATA:state.game===4?SIGNAL_SCANNER_DATA:state.game===3?SUPPLY_SEARCH_DATA:state.game===2?STREET_SIGNALS_DATA:GRAMMAR_DATA;}
function showQuestion(){if(state.game===3){showTypingQuestion();return;}locked=false;state.lives=3;updateHud();clearScreen();const questions=currentGrammarData(),question=questions[state.questionIndex];const stage=document.createElement('div');stage.className='question-stage';if(state.game===2)stage.style.backgroundImage=`linear-gradient(#07101aaa,#090503c7),url('${ASSETS.blackoutStreet}')`;if(state.game===4){stage.classList.add('signal-stage');stage.style.backgroundImage=`linear-gradient(#07101aaa,#090503c7),url('${ASSETS.serviceTunnels}')`;}const panel=document.createElement('div');panel.className='question-panel';const copy=document.createElement('div');copy.className='question-copy';const title=state.game===4?'GAME 4 — SIGNAL SCANNER':state.game===2?'GAME 2 — STREET SIGNALS':'GAME 1 — EMERGENCY PHONE',instruction=state.game===4?'Find the correct sentence.':'Choose the correct answer.';copy.innerHTML=`<p class="eyebrow">${title}</p><p class="instruction">${instruction}</p><p class="sentence"></p>`;copy.querySelector('.sentence').textContent=question.sentence||'';const answers=document.createElement('div');answers.className='answers';const sizingOptions=state.game===4&&state.questionIndex===0?questions[1].options:question.options,longestOptionLength=Math.max(...sizingOptions.map(option=>option.length)),gameFourSizeClass=longestOptionLength>62?'answer-long':longestOptionLength>48?'answer-medium':'answer-short';question.options.forEach(option=>{const answer=document.createElement('button');const answerCopy=document.createElement('span');answer.className='answer';answerCopy.className='answer-copy';if(state.game===4)answerCopy.classList.add(gameFourSizeClass);answerCopy.textContent=option;answer.append(answerCopy);answer.setAttribute('aria-label',option);answer.onclick=()=>answerQuestion(answer,option);answers.append(answer);});panel.append(copy,answers);stage.append(panel);screen.append(stage);if(state.energy===0)showEnergyRecovery();}
function answerQuestion(buttonElement,choice){if(locked)return;const question=currentGrammarData()[state.questionIndex];if(choice===question.answer){locked=true;buttonElement.classList.add('correct');document.querySelectorAll('.answer').forEach(answer=>answer.disabled=true);state.correctAnswers++;if(state.lives===3)state.firstAttemptCorrect++;state.streak++;state.maxStreak=Math.max(state.maxStreak,state.streak);state.score+=CONFIG.multipleChoiceScore;if(state.game===2||state.game===4)state.gameProgress++;audio.sfx('correct');updateHud();showFeedback(`CORRECT +${CONFIG.multipleChoiceScore}`,'good',1450);transitionId=setTimeout(nextQuestion,1500);return;}buttonElement.classList.add('wrong');setTimeout(()=>buttonElement.classList.remove('wrong'),500);audio.sfx('wrong');state.wrongAnswers++;state.streak=0;state.lives=Math.max(0,state.lives-1);state.livesLost++;updateHud();showFeedback(state.lives===0?'WRONG — EMERGENCY RESCUE':'WRONG — TRY AGAIN','bad');const depleted=loseEnergyForWrongAnswer();if(depleted)return;if(state.lives===0){locked=true;document.querySelectorAll('.answer').forEach(answer=>answer.disabled=true);transitionId=setTimeout(launchEmergencyRescue,750);}}
function nextQuestion(){state.questionIndex++;if(state.questionIndex<currentGrammarData().length)showQuestion();else if(state.game===1)showGameOneComplete();else if(state.game===2)showGameTwoComplete();else showServiceTunnelsComplete();}
function showGameOneComplete(){audio.sfx('complete');clearScreen();screen.style.backgroundImage=`url('${ASSETS.home}')`;const streetReady=preloadImage(ASSETS.blackoutStreet);const success=document.createElement('div');success.className='mission-success';success.innerHTML='<h2>SECURITY CHECK COMPLETE ✓</h2><p>GAME 1 COMPLETE</p>';screen.append(success);transitionId=setTimeout(async()=>{await streetReady;showBlackoutStreet();},1900);}
function showBlackoutStreet(){clearScreen();screen.classList.add('scene-arrival');screen.style.backgroundImage=`url('${ASSETS.blackoutStreet}')`;const location=document.createElement('div');location.className='street-copy';location.innerHTML='<h2>BLACKOUT STREET</h2><p>Emergency signals are appearing across the city.</p><strong>NEXT OBJECTIVE: STREET SIGNALS</strong>';screen.append(location);transitionId=setTimeout(()=>{state.game=2;state.questionIndex=0;state.gameProgress=0;showQuestion();},BETWEEN_GAME_TRANSITION_MS);}
function showGameTwoComplete(){audio.sfx('complete');clearScreen();screen.style.backgroundImage=`url('${ASSETS.blackoutStreet}')`;const success=document.createElement('div');success.className='mission-success';success.innerHTML='<h2>STREET SIGNALS COMPLETE ✓</h2><p>GAME 2 COMPLETE</p>';screen.append(success);transitionId=setTimeout(showSupplySearchIntro,1900);}
function showSupplySearchIntro(){clearScreen();screen.classList.add('scene-arrival');screen.style.backgroundImage=`url('${ASSETS.supplyRoom}')`;const location=document.createElement('div');location.className='street-copy';location.innerHTML='<h2>SUPPLY SEARCH</h2><p>Search the supply room for essential items.</p><strong>NEXT OBJECTIVE: RECOVER SUPPLIES</strong>';screen.append(location);transitionId=setTimeout(()=>{state.game=3;state.questionIndex=0;state.gameProgress=0;showQuestion();},BETWEEN_GAME_TRANSITION_MS);}
function normalizeTypedAnswer(value){return value.trim().toLowerCase().replace(/[‘’]/g,"'").replace(/\s+/g,' ');}
function showTypingQuestion(){locked=false;state.lives=3;updateHud();clearScreen();const question=SUPPLY_SEARCH_DATA[state.questionIndex];const stage=document.createElement('div');stage.className='question-stage typing-stage';stage.style.backgroundImage=`linear-gradient(#07101aaa,#090503c7),url('${ASSETS.supplyRoom}')`;const panel=document.createElement('div');panel.className='question-panel';const copy=document.createElement('div');copy.className='question-copy';copy.innerHTML='<p class="eyebrow">GAME 3 — SUPPLY SEARCH</p><p class="instruction">Type the correct verb form.</p><p class="sentence"></p>';copy.querySelector('.sentence').textContent=question.sentence;const controls=document.createElement('form');controls.className='typing-controls';controls.innerHTML='<input class="typing-input" type="text" placeholder="Type your answer..." autocomplete="off" aria-label="Type the correct verb form"><button type="submit">CHECK</button>';controls.onsubmit=event=>{event.preventDefault();submitTypedAnswer(controls.querySelector('.typing-input'));};panel.append(copy,controls);stage.append(panel);screen.append(stage);controls.querySelector('.typing-input').focus();if(state.energy===0)showEnergyRecovery();}
function submitTypedAnswer(input){if(locked)return;const question=SUPPLY_SEARCH_DATA[state.questionIndex];if(normalizeTypedAnswer(input.value)===normalizeTypedAnswer(question.answer)){locked=true;input.disabled=true;input.form.querySelector('button').disabled=true;state.correctAnswers++;if(state.lives===3)state.firstAttemptCorrect++;state.streak++;state.maxStreak=Math.max(state.maxStreak,state.streak);state.score+=CONFIG.multipleChoiceScore;state.gameProgress++;audio.sfx('correct');updateHud();showFeedback(`CORRECT +${CONFIG.multipleChoiceScore}`,'good',1450);transitionId=setTimeout(()=>awardSupplyItem(question),650);return;}input.classList.remove('wrong');void input.offsetWidth;input.classList.add('wrong');audio.sfx('wrong');state.wrongAnswers++;state.streak=0;state.lives=Math.max(0,state.lives-1);state.livesLost++;updateHud();showFeedback(state.lives===0?'WRONG — EMERGENCY RESCUE':'WRONG — TRY AGAIN','bad');const depleted=loseEnergyForWrongAnswer();if(depleted)return;if(state.lives===0){locked=true;input.disabled=true;input.form.querySelector('button').disabled=true;transitionId=setTimeout(launchEmergencyRescue,750);return;}input.focus();input.select();}
function awardSupplyItem(question){if(state.inventory.includes(question.reward)){advanceSupplySearch();return;}audio.sfx('itemPickup');const reward=document.createElement('div');reward.className='item-found';reward.innerHTML=`<div class="reward-card"><p>SUPPLY ACQUIRED</p><img src="${question.asset}" alt="${question.reward}"><strong>${question.reward.toUpperCase()}</strong></div>`;screen.append(reward);const item=reward.querySelector('img');transitionId=setTimeout(()=>{state.inventory.push(question.reward);const itemBox=item.getBoundingClientRect(),backpackBox=document.querySelector('.backpack-icon').getBoundingClientRect();item.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${backpackBox.left+backpackBox.width/2-itemBox.left-itemBox.width/2}px,${backpackBox.top+backpackBox.height/2-itemBox.top-itemBox.height/2}px) scale(.12)`,opacity:0}],{duration:900,easing:'ease-in',fill:'forwards'}).finished.then(()=>{updateHud();document.querySelector('#backpack').classList.add('collect-pulse');setTimeout(()=>document.querySelector('#backpack').classList.remove('collect-pulse'),650);advanceSupplySearch();});},1500);}
function advanceSupplySearch(){state.questionIndex++;if(state.questionIndex<SUPPLY_SEARCH_DATA.length)showQuestion();else showGameThreeComplete();}
function showGameThreeComplete(){audio.sfx('complete');clearScreen();screen.style.backgroundImage=`url('${ASSETS.supplyRoom}')`;const success=document.createElement('div');success.className='mission-success';success.innerHTML='<h2>SUPPLIES SECURED ✓</h2><p>GAME 3 COMPLETE</p>';screen.append(success);transitionId=setTimeout(showRouteSelection,1900);}
function showRouteSelection(){clearTimeout(routeMessageId);clearScreen();const composition=artComposition(ASSETS.routeSelection,'Route Selection: Service Tunnels, City Streets, Main Bridge');composition.classList.add('route-selection');const allComplete=state.serviceTunnelsCompleted&&state.cityStreetsCompleted&&state.mainBridgeCompleted;const baseInstruction=allComplete?'<strong>ALL ROUTES COMPLETE ✓</strong><span>CITY NETWORK MAPPED</span>':state.cityStreetsCompleted?'<strong>FINAL ROUTE UNLOCKED</strong><span>Cross the Main Bridge.</span>':state.serviceTunnelsCompleted?'<strong>NEXT ROUTE UNLOCKED</strong><span>Proceed through City Streets.</span>':'<strong>SERVICE TUNNELS AVAILABLE</strong><span>Complete the routes in sequence.</span>';const instruction=document.createElement('div');instruction.className='route-instruction';instruction.innerHTML=baseInstruction;const routes=[['serviceTunnels','serviceTunnelsCompleted','Service Tunnels'],['cityStreets','cityStreetsCompleted','City Streets'],['mainBridge','mainBridgeCompleted','Main Bridge']];routes.forEach(([route,key,label],index)=>{const completed=state[key],available=!allComplete&&((route==='serviceTunnels'&&!state.serviceTunnelsCompleted)||(route==='cityStreets'&&state.serviceTunnelsCompleted&&!state.cityStreetsCompleted)||(route==='mainBridge'&&state.cityStreetsCompleted&&!state.mainBridgeCompleted)),routeState=completed?'completed':available?'available':'locked';const choice=button(`route-choice route-${index+1} ${routeState}`,`${label}: ${routeState}`);choice.disabled=completed;choice.innerHTML=completed?'✓ COMPLETED':routeState==='locked'?'🔒 LOCKED':'';choice.onclick=()=>{if(available)selectRoute(route,label);else if(!completed)showRouteLocked(route,instruction,baseInstruction);};const shade=document.createElement('div');shade.className=`route-card-shade route-card-${index+1} ${routeState}`;composition.append(choice,shade);});composition.append(instruction);screen.append(composition);}
function showRouteLocked(route,instruction,baseInstruction){const requirement=route==='cityStreets'||!state.serviceTunnelsCompleted?'Complete Service Tunnels first.':'Complete City Streets first.';instruction.innerHTML=`<strong>ROUTE LOCKED</strong><span>${requirement}</span>`;clearTimeout(routeMessageId);routeMessageId=setTimeout(()=>instruction.innerHTML=baseInstruction,1800);}
function selectRoute(route,label){state.selectedRoute=route;audio.sfx('select');if(route==='serviceTunnels'){showServiceTunnelsIntro();return;}if(route==='cityStreets'){showCityStreetsIntro();return;}const instruction=document.querySelector('.route-instruction');if(instruction)instruction.innerHTML=`<strong>${label.toUpperCase()} SELECTED</strong><span>Route gameplay will continue here.</span>`;}
function showServiceTunnelsIntro(){clearScreen();screen.classList.add('scene-arrival');screen.style.backgroundImage=`url('${ASSETS.serviceTunnels}')`;const location=document.createElement('div');location.className='street-copy';location.innerHTML='<h2>SERVICE TUNNELS</h2><p>A safer path beneath the city.</p><strong>NEXT OBJECTIVE: RESTORE THE SIGNAL</strong>';screen.append(location);transitionId=setTimeout(()=>{state.game=4;state.questionIndex=0;state.gameProgress=0;showQuestion();},BETWEEN_GAME_TRANSITION_MS);}
function showServiceTunnelsComplete(){state.serviceTunnelsCompleted=true;audio.sfx('complete');clearScreen();screen.style.backgroundImage=`url('${ASSETS.serviceTunnels}')`;const success=document.createElement('div');success.className='mission-success';success.innerHTML='<h2>SIGNAL RESTORED ✓</h2><p>SERVICE TUNNELS COMPLETE</p>';screen.append(success);transitionId=setTimeout(showRouteSelection,1900);}
function showCityStreetsIntro(){clearScreen();screen.classList.add('scene-arrival');screen.style.backgroundImage=`url('${ASSETS.cityStreets}')`;const location=document.createElement('div');location.className='street-copy';location.innerHTML='<h2>CITY STREETS</h2><p>Signal interference detected.</p><strong>NEXT OBJECTIVE: TRACE THE EMERGENCY TRANSMISSION</strong>';screen.append(location);transitionId=setTimeout(()=>{state.game=5;state.questionIndex=0;state.gameProgress=0;showErrorDetectorQuestion();},CITY_TRANSITION_MS);}
function showErrorDetectorQuestion(){locked=false;state.lives=3;updateHud();clearScreen();const question=ERROR_DETECTOR_DATA[state.questionIndex];const stage=document.createElement('div');stage.className='question-stage detector-stage';stage.style.backgroundImage=`linear-gradient(#07101aaa,#090503c7),url('${ASSETS.cityStreets}')`;const panel=document.createElement('div');panel.className='question-panel';const copy=document.createElement('div');copy.className='question-copy';copy.innerHTML='<p class="eyebrow">GAME 5 — ERROR DETECTOR</p><p class="instruction">Find the grammar mistake.</p><p class="sentence"></p>';copy.querySelector('.sentence').textContent=question.sentence;const segments=document.createElement('div');segments.className='detector-segments';question.segments.forEach(segment=>{const choice=document.createElement('button');choice.type='button';choice.className='detector-segment';choice.textContent=segment;choice.onclick=()=>answerErrorDetector(choice,segment);segments.append(choice);});panel.append(copy,segments);stage.append(panel);screen.append(stage);if(state.energy===0)showEnergyRecovery();}
function answerErrorDetector(buttonElement,segment){if(locked)return;const question=ERROR_DETECTOR_DATA[state.questionIndex];if(segment===question.wrong){locked=true;buttonElement.classList.add('correct');document.querySelectorAll('.detector-segment').forEach(button=>button.disabled=true);state.correctAnswers++;if(state.lives===3)state.firstAttemptCorrect++;state.streak++;state.maxStreak=Math.max(state.maxStreak,state.streak);state.score+=CONFIG.multipleChoiceScore;state.gameProgress++;audio.sfx('correct');updateHud();showFeedback(`CORRECT — ${question.correction}`,'good',2200);const sentence=document.querySelector('.detector-stage .sentence');sentence.textContent=question.corrected;sentence.classList.add('corrected');transitionId=setTimeout(nextErrorDetectorQuestion,2300);return;}buttonElement.classList.add('wrong');setTimeout(()=>buttonElement.classList.remove('wrong'),500);audio.sfx('wrong');state.wrongAnswers++;state.streak=0;state.lives=Math.max(0,state.lives-1);state.livesLost++;updateHud();showFeedback(state.lives===0?'WRONG — EMERGENCY RESCUE':'WRONG — TRY AGAIN','bad');const depleted=loseEnergyForWrongAnswer();if(depleted)return;if(state.lives===0){locked=true;document.querySelectorAll('.detector-segment').forEach(button=>button.disabled=true);transitionId=setTimeout(launchEmergencyRescue,750);}}
function nextErrorDetectorQuestion(){state.questionIndex++;if(state.questionIndex<ERROR_DETECTOR_DATA.length)showErrorDetectorQuestion();else showCityStreetsComplete();}
function showCityStreetsComplete(){audio.sfx('complete');clearScreen();screen.style.backgroundImage=`url('${ASSETS.cityStreets}')`;const success=document.createElement('div');success.className='mission-success';success.innerHTML='<h2>TRANSMISSION LOCATED</h2><p>CITY STREETS COMPLETE ✓</p>';screen.append(success);transitionId=setTimeout(()=>{state.cityStreetsCompleted=true;showRouteSelection();},CITY_TRANSITION_MS);}
function completeRoute(route){const key={serviceTunnels:'serviceTunnelsCompleted',cityStreets:'cityStreetsCompleted',mainBridge:'mainBridgeCompleted'}[route];if(key)state[key]=true;state.selectedRoute=null;showRouteSelection();}
async function launchEmergencyRescue(){await preloadImage(ASSETS.emergencyRescue);state.rescueIndex=0;state.rescueCorrect=0;renderRescueQuestion();}
function renderRescueQuestion(){clearScreen();const rescue=RESCUE_DATA[state.rescueIndex];const stage=document.createElement('div');stage.className='rescue-stage';const content=document.createElement('div');content.className='rescue-content';content.innerHTML=`<h2>EMERGENCY RESCUE</h2><p class="rescue-instruction">Choose the correct answer. Get 3 out of 5 to continue.</p><p class="rescue-progress">${state.rescueIndex+1} / 5</p><p class="rescue-sentence"></p><div class="rescue-answers"></div>`;content.querySelector('.rescue-sentence').textContent=rescue.sentence;const answers=content.querySelector('.rescue-answers');rescue.options.forEach(option=>{const choice=document.createElement('button');choice.type='button';choice.textContent=option;choice.onclick=()=>answerRescue(choice,option);answers.append(choice);});stage.append(content);screen.append(stage);}
function answerRescue(buttonElement,choice){document.querySelectorAll('.rescue-answers button').forEach(button=>button.disabled=true);const correct=choice===RESCUE_DATA[state.rescueIndex].answer;buttonElement.classList.add(correct?'correct':'wrong');if(correct){state.rescueCorrect++;audio.sfx('correct');}else audio.sfx('wrong');transitionId=setTimeout(()=>{state.rescueIndex++;if(state.rescueIndex<RESCUE_DATA.length)renderRescueQuestion();else finishEmergencyRescue();},650);}
function finishEmergencyRescue(){clearScreen();const result=document.createElement('div');result.className='rescue-result';if(state.rescueCorrect>=3){state.emergencyRescueCount++;result.innerHTML=`<h2>RESCUE SUCCESSFUL</h2><p>${state.rescueCorrect}/5 CORRECT</p>`;screen.append(result);if(state.game===5){transitionId=setTimeout(showErrorDetectorQuestion,1200);return;}if(state.game===3){state.gameProgress++;transitionId=setTimeout(()=>awardSupplyItem(SUPPLY_SEARCH_DATA[state.questionIndex]),1200);return;}if(state.game===2||state.game===4)state.gameProgress++;state.questionIndex++;transitionId=setTimeout(()=>{if(state.questionIndex<currentGrammarData().length)showQuestion();else if(state.game===1)showGameOneComplete();else if(state.game===2)showGameTwoComplete();else showServiceTunnelsComplete();},1200);}else{result.innerHTML=`<h2>MISSION FAILED / RESCUE FAILED</h2><p>${state.rescueCorrect}/5 CORRECT</p>`;const retry=document.createElement('button');retry.type='button';retry.textContent='RETRY EMERGENCY RESCUE';retry.onclick=()=>{audio.sfx('click');launchEmergencyRescue();};result.append(retry);screen.append(result);}}
function renderAudioPanel(){const panel=document.createElement('section');panel.className='audio-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Audio settings');panel.innerHTML=`<h2>AUDIO</h2><label><span>MUSIC</span><input id="music-volume" type="range" min="0" max="1" step=".05" value="${audio.musicVolume}"><output>${Math.round(audio.musicVolume*100)}%</output></label><label><span>SFX</span><input id="sfx-volume" type="range" min="0" max="1" step=".05" value="${audio.sfxVolume}"><output>${Math.round(audio.sfxVolume*100)}%</output></label><button id="mute-audio" type="button">${audio.muted?'UNMUTE':'MUTE'}</button>`;modalRoot.replaceChildren(panel);const music=panel.querySelector('#music-volume'),sfx=panel.querySelector('#sfx-volume');music.oninput=()=>{audio.setMusicVolume(music.value);music.nextElementSibling.textContent=`${Math.round(music.value*100)}%`;};sfx.oninput=()=>{audio.setSfxVolume(sfx.value);sfx.nextElementSibling.textContent=`${Math.round(sfx.value*100)}%`;};panel.querySelector('#mute-audio').onclick=event=>{event.stopPropagation();event.currentTarget.textContent=audio.toggleMute()?'UNMUTE':'MUTE';updateAudioIcon();};panel.onclick=event=>event.stopPropagation();return panel;}
function toggleAudioPanel(forceOpen=false){const open=modalRoot.firstElementChild;if(open&&!forceOpen){closeAudioPanel();return;}if(!open)renderAudioPanel();audioToggle.setAttribute('aria-expanded','true');}
function closeAudioPanel(){modalRoot.replaceChildren();audioToggle.setAttribute('aria-expanded','false');}
function showEnergyRecovery(){locked=true;document.querySelectorAll('.answer,.typing-input,.typing-controls button,.detector-segment').forEach(control=>control.disabled=true);const recoveryItems=[['Water Bottle',ASSETS.items.waterBottle],['Chocolate Bar',ASSETS.items.chocolateBar],['Batteries',ASSETS.items.batteries]].filter(([name])=>state.inventory.includes(name));const panel=document.createElement('section');panel.className='energy-recovery';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','Energy depleted');panel.innerHTML='<h2>ENERGY DEPLETED</h2><p>Use a supply from your backpack<br>to restore your energy.</p><div class="energy-supplies"></div>';const supplies=panel.querySelector('.energy-supplies');recoveryItems.forEach(([name,asset])=>{const use=document.createElement('button');use.type='button';use.innerHTML=`<img src="${asset}" alt=""><span>${name.toUpperCase()}</span>`;use.onclick=event=>{event.stopPropagation();useEnergySupply(name);};supplies.append(use);});if(!recoveryItems.length){const empty=document.createElement('strong');empty.className='energy-empty';empty.textContent='NO ENERGY SUPPLIES AVAILABLE';supplies.append(empty);}panel.onclick=event=>event.stopPropagation();modalRoot.replaceChildren(panel);}
function useEnergySupply(name){const itemIndex=state.inventory.indexOf(name);if(itemIndex<0)return;state.inventory.splice(itemIndex,1);state.energy=CONFIG.maxEnergy;updateHud();modalRoot.replaceChildren();if(state.lives===0){transitionId=setTimeout(launchEmergencyRescue,250);return;}locked=false;document.querySelectorAll('.answer,.typing-input,.typing-controls button,.detector-segment').forEach(control=>control.disabled=false);const input=document.querySelector('.typing-input');if(input){input.focus();input.select();}}
function renderInventoryPanel(){const panel=document.createElement('section');panel.className='inventory-popup';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Backpack inventory');panel.innerHTML='<h2>BACKPACK</h2><div class="inventory-slots"></div>';const slots=panel.querySelector('.inventory-slots');SUPPLY_SEARCH_DATA.forEach(item=>{const collected=state.inventory.includes(item.reward);const slot=document.createElement('div');slot.className=`inventory-slot ${collected?'collected':'empty'}`;slot.innerHTML=`<img src="${item.asset}" alt=""><span>${item.reward.toUpperCase()}</span>`;slots.append(slot);});modalRoot.replaceChildren(panel);document.querySelector('#backpack').setAttribute('aria-expanded','true');panel.onclick=event=>event.stopPropagation();}
function toggleInventoryPanel(){if(modalRoot.querySelector('.inventory-popup')){modalRoot.replaceChildren();document.querySelector('#backpack').setAttribute('aria-expanded','false');return;}renderInventoryPanel();}
audioToggle.onclick=event=>{event.stopPropagation();audio.unlock();toggleAudioPanel();};document.addEventListener('pointerdown',event=>{if(modalRoot.firstElementChild&&!modalRoot.querySelector('.energy-recovery')&&!modalRoot.contains(event.target)&&event.target!==audioToggle)closeAudioPanel();});
document.querySelector('#backpack').onclick=event=>{event.stopPropagation();audio.sfx('inventory');toggleInventoryPanel();};
function startDevMode(){if(!DEV_TARGET||!LOCAL_DEV_HOSTS.has(location.hostname))return false;const targets=new Set(['home','game1','street','game2','game3','routes','service-tunnels','city-streets','routes-after-city','rescue']);if(!targets.has(DEV_TARGET))return false;const energyValue=new URLSearchParams(location.search).get('energy'),parsedEnergy=Number(energyValue),devEnergy=energyValue!==null&&energyValue.trim()!==''&&Number.isFinite(parsedEnergy)?Math.max(0,Math.min(CONFIG.maxEnergy,parsedEnergy)):75;state.reset();Object.assign(state,{score:1000,energy:devEnergy,lives:3,secrets:0,startedAt:Date.now()});if(['routes','service-tunnels','city-streets','routes-after-city'].includes(DEV_TARGET))state.inventory=SUPPLY_SEARCH_DATA.map(item=>item.reward);hud.classList.remove('hidden');updateHud();startTimer();armDevAudioUnlock();if(DEV_TARGET==='home')showHome();else if(DEV_TARGET==='game1'){state.game=1;showQuestion();}else if(DEV_TARGET==='street')showBlackoutStreet();else if(DEV_TARGET==='game2'){state.game=2;state.questionIndex=0;state.gameProgress=0;showQuestion();}else if(DEV_TARGET==='game3'){state.game=3;state.questionIndex=0;state.gameProgress=0;showQuestion();}else if(DEV_TARGET==='routes')showRouteSelection();else if(DEV_TARGET==='service-tunnels'){state.game=4;state.questionIndex=0;state.gameProgress=0;state.serviceTunnelsCompleted=false;showQuestion();}else if(DEV_TARGET==='city-streets'){state.game=5;state.questionIndex=0;state.gameProgress=0;state.serviceTunnelsCompleted=true;state.cityStreetsCompleted=false;showErrorDetectorQuestion();}else if(DEV_TARGET==='routes-after-city'){state.serviceTunnelsCompleted=true;state.cityStreetsCompleted=true;state.mainBridgeCompleted=false;showRouteSelection();}else{state.game=1;state.questionIndex=0;launchEmergencyRescue();}return true;}
async function initialLoad(){const required=[ASSETS.start,ASSETS.how,ASSETS.home,ASSETS.hud,ASSETS.life,ASSETS.phone,ASSETS.question];let done=0;const bar=document.querySelector('#load-bar'),value=document.querySelector('#load-value');await Promise.all(required.map(src=>new Promise(resolve=>{const image=new Image();const finish=()=>{done++;const percent=Math.round(done/required.length*100);bar.style.width=`${percent}%`;value.textContent=`${percent}%`;resolve();};image.onload=finish;image.onerror=finish;image.src=src;})));setTimeout(()=>{document.querySelector('#loading').classList.add('hidden');updateAudioIcon();if(!startDevMode())showStart();},250);}
initialLoad();
