// No dependencies. Run from any directory with Node.js 18 or newer.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex').slice(0,20);
const assetPattern=/assets\/[^\s'"<>`?)]+\.(?:webp|png|jpe?g|svg|mp3|wav|ogg)/g;
function prepare(overrides=new Map()) {
 const read=file=>overrides.get(file)??fs.readFileSync(path.join(root,file));
 const script=read('script.js').toString(),css=read('style.css').toString(),html=read('index.html').toString();
 for(const [name,text] of [['script.js',script],['style.css',css],['index.html',html]]) {
  if(/(?:["'`(=])\s*\/(?:assets\/|script\.js|style\.css)|localhost:\d|\/Users\//.test(text))throw Error(`Unsafe deployment path in ${name}`);
 }
 const context=vm.createContext({});
 // Evaluate only declarative asset definitions; never execute game startup.
 vm.runInContext(script.slice(0,script.indexOf('const GRAMMAR_DATA'))+'\nthis.inventory={ASSETS,SFX,AUDIO_TRACKS,NIGHTFALL_COLLECTIBLES,achievements:FINAL_ACHIEVEMENT_DEFINITIONS.map(row=>achievementAsset(row[2]))};this.canonical=runtimeImage;',context);
 const files=new Set();
 const add=value=>{if(typeof value==='string'&&/^assets\/.*\.(webp|png|jpe?g|svg|mp3|wav|ogg)$/.test(value))files.add(context.canonical(value));else if(value&&typeof value==='object')Object.values(value).forEach(add);};
 add(context.inventory);
 for(const text of [script,css,html])for(const match of text.matchAll(assetPattern))add(match[0]);
 const urls={};
 for(const file of [...files].sort()) {
  if(file.includes('..')||!fs.statSync(path.join(root,file)).isFile())throw Error(`Missing/unsafe resource: ${file}`);
  urls[file]=`${file}?v=${hash(read(file))}`;
 }
 const manifest='// Generated by tools/prepare-release.mjs; do not edit.\n'+'globalThis.BLACKOUT_ASSET_URLS=Object.freeze('+JSON.stringify(urls,null,2)+');\n';
 // Strip previous generated hashes before recalculating. CSS URLs share the JS manifest identity.
 const versionAssets=text=>text.replace(/(assets\/[^\s'"<>`?)]+\.(?:webp|png|jpe?g|svg|mp3|wav|ogg))(?:\?v=[a-f0-9]+)?/g,(_,file)=>urls[context.canonical(file)]||(()=>{throw Error(`Unmapped resource: ${file}`);})());
 const runtimeContext=vm.createContext({});
 vm.runInContext(manifest+script.slice(0,script.indexOf('class AudioManager'))+script.slice(script.indexOf('const SECTION_ASSETS='),script.indexOf('const sectionReadiness='))+'\nthis.sections=SECTION_ASSETS;',runtimeContext);
 for(const [section,sources] of runtimeContext.sections)for(const url of sources)if(!Object.values(urls).includes(url))throw Error(`Unversioned readiness URL in ${section}: ${url}`);
 const nextCss=versionAssets(css);
 let nextHtml=versionAssets(html).replace(/(?:  )?<script src="release-assets\.js(?:\?v=[a-f0-9]+)?"><\/script>\n?/g,'');
 nextHtml=nextHtml.replace(/href="style\.css(?:\?v=[a-f0-9]+)?"/,`href="style.css?v=${hash(nextCss)}"`).replace(/<script src="script\.js(?:\?v=[a-f0-9]+)?"><\/script>/,`<script src="release-assets.js?v=${hash(manifest)}"></script>\n  <script src="script.js?v=${hash(script)}"></script>`);
 return {urls,outputs:{'release-assets.js':manifest,'style.css':nextCss,'index.html':nextHtml,'.nojekyll':''}};
}
function simulation() {
 const a=prepare(),b=prepare();
 if(JSON.stringify(a)!==JSON.stringify(b))throw Error('Non-deterministic generation');
 for(const file of ['script.js','style.css',Object.keys(a.urls).find(x=>/\.webp$/.test(x)),Object.keys(a.urls).find(x=>/\.mp3$/.test(x))]) {
  const bytes=Buffer.concat([fs.readFileSync(path.join(root,file)),Buffer.from('\n/* release fixture */\n')]);
  const changed=prepare(new Map([[file,bytes]]));
  for(const asset of Object.keys(a.urls))if((a.urls[asset]!==changed.urls[asset])!==(asset===file))throw Error(`Incorrect asset invalidation: ${asset}`);
  if(file==='script.js'&&a.outputs['index.html']===changed.outputs['index.html'])throw Error('JS identity did not change');
  if(file==='style.css'&&a.outputs['index.html']===changed.outputs['index.html'])throw Error('CSS identity did not change');
  if(file.startsWith('assets/')&&a.outputs['release-assets.js']===changed.outputs['release-assets.js'])throw Error('Manifest did not change');
 }
 console.log('Two-release byte fixtures passed: JS, CSS, image, audio; unchanged asset URLs stable. No game files modified.');
}
try {
 if(process.argv.includes('--self-test'))simulation();
 const result=prepare();
 if(process.argv.includes('--check')) {
  for(const [file,text] of Object.entries(result.outputs))if(!fs.existsSync(path.join(root,file))||fs.readFileSync(path.join(root,file),'utf8')!==text)throw Error(`Stale generated file: ${file}; run node tools/prepare-release.mjs`);
 }else for(const [file,text] of Object.entries(result.outputs))fs.writeFileSync(path.join(root,file),text);
 console.log(`Validated ${Object.keys(result.urls).length} canonical runtime resources. ${process.argv.includes('--check')?'Release is current.':'Release references regenerated.'}`);
}catch(error){console.error(error.message);process.exitCode=1;}
